# Hugo variables
#
baseurl = "https://alanorth.github.io/cgspace-notes/"
languageCode = "en-us"
title = "CGSpace Notes"
newContentEditor = "vim"
theme = "vienna"

[permalinks]
  # use 2016-09 as slug, since my posts are always monthly
  post = "/:year-:month/"

[params]
  # Site author
  author = "Alan Orth"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  [params.sidebar]
    # Hide the sidebar? (Default: false)
    hide = false

  [params.sharingicons]
    hide = true
