baseurl = "https://alanorth.github.io/cgspace-notes/"
languageCode = "en-us"
title = "CGSpace Notes"
newContentEditor = "vim"
theme = "vienna"

[permalinks]
  # use 2016-09 as slug, since my posts are always monthly
  post = "/:year-:month/"

[params]
  author = "Alan Orth"
