# Hugo variables
#
baseurl = "https://alanorth.github.io/cgspace-notes/"
languageCode = "en-us"
title = "CGSpace Notes"
newContentEditor = "vim"
theme = "hugo-theme-bootstrap4-blog"
enableRobotsTXT = true
enableGitInfo = true
publishDir = "docs"

[permalinks]
  # use 2016-09 as slug, since my posts are always monthly
  post = "/:year-:month/"

[params]
  # Site author
  author = "Alan Orth"

  # Description/subtitle for homepage (can be Markdown)
  description = "Documenting day-to-day work on the [CGSpace](https://cgspace.cgiar.org) repository."
  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  sharingicons = false

  [params.sidebar]
    # Hide the sidebar? (Default: false)
    hide = false

[[menu.sidebar]]
  name = "CGSpace"
  url = "https://cgspace.cgiar.org"
  weight = 1

[[menu.sidebar]]
  name = "DSpace Test"
  url = "https://dspacetest.cgiar.org"
  weight = 2

[[menu.sidebar]]
  name = "CGSpace @ GitHub"
  url = "https://github.com/ilri/DSpace"
  weight = 3
